# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hospitalmanagement' do
   
  target 'test_google_signin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test_google_signin
  pod 'GoogleSignIn'

  target 'hospitalmanagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

end
